package com.codecool.keepcash.Service.Validation;

public enum  ValidationError {
    AT_LEAST_ONE_VALUE_IS_NULL,
    FIRST_NAME_NOT_VALID,
    LAST_NAME_NOT_VALID,
    EMAIL_NOT_VALID,
    PASSWORD_NOT_VALID,
    EMAIL_ALREADY_IN_DB,
    USERNAME_ALREADY_IN_DB, USERNAME_NOT_VALID,
    NO_CATEGORY_IN_DB, NO_ACCOUNT_IN_DB, TO_LONG_DESCRIPTION,
    TO_LONG_NAME, NAME_ALREADY_IN_DB
}
