package com.codecool.keepcash.Service.Validation;

public enum  ValidationError {
    AT_LEAST_ONE_VALUE_IS_NULL,
    FIRST_NAME_NOT_VALID,
    LAST_NAME_NOT_VALID,
    EMAIL_NOT_VALID,
    PASSWORD_NOT_VALID,
    USERNAME_NOT_VALID,
    EMAIL_ALREADY_IN_DB,
    USERNAME_ALREADY_IN_DB,
    OLD_EMAIL_DOESNT_MATCH,
    NEW_EMAIL_DOESNT_MATCH_CONFIRMED,
    NEW_EMAIL_SAME_AS_OLD_EMAIL,
    NEW_PASSWORD_DOESNT_MATCH_CONFIRMED_PASSWORD,
    WRONG_PASSWORD_FOR_GIVEN_USER
}
